# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_ACTIONS: 1

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.platform }}

    env:
      PLATFORM: ${{ matrix.platform }}
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox
    - name: Test
      run: nox -p ${PYTHON} -t actions-test
      if: ${{ matrix.platform != 'windows-latest' }}
    - name: Test
      run: nox -p ${env:PYTHON} -t actions-test
      if: ${{ matrix.platform == 'windows-latest' }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        env_vars: PLATFORM,PYTHON
        files: ./coverage.xml

  check:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8"]

    runs-on: ${{ matrix.platform }}

    env:
      PLATFORM: ${{ matrix.platform }}
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox
    - name: Lint, build docs, and package
      run: nox -t actions-check
    - name: Upload docs
      uses: actions/upload-artifact@v3
      with:
        name: docs-${{ matrix.platform }}
        path: build/sphinx/html
    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: packages-${{ matrix.platform }}
        path: |
          dist
          marbles/core/dist
          marbles/mixins/dist
